/*
SCRIVERE UN PROGRAMMA IN C CHE:
1. ALLOCHI DINAMICAMENTE UN ARRAY INIZIALE DI N NUMERI
2. INSERISCI DEI VALORI
3. STAMPA ARRAY
4. CALCOLI LA SOMMA DEGLI ELEMENTI MULTIPLI DI 3
5. CREIAMO UN NUOVO ARRAY CONTENENTE SOLO VALORI DISPARI
*/
#include <stdio.h>
#include <stdlib.h>


